"""add national ID and DOB

Revision ID: 3fd74124ed08
Revises: 2371e779bf42
Create Date: 2025-03-23 13:32:57.663950

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fd74124ed08"
down_revision: str | None = "2371e779bf42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("national_id", sa.String(), nullable=False))
    op.add_column("user", sa.Column("date_of_birth", sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "date_of_birth")
    op.drop_column("user", "national_id")
    # ### end Alembic commands ###
